name: Process Lyricify Syllable Lyrics

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  process_lyrics:
    if: contains(github.event.issue.labels.*.name, 'TTML to LYS') # 只在标签匹配时运行
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install loguru PyGithub

      - name: Process Lyrics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python3 ttml_to_lys_on_github.py

      - name: Close Issue
        if: success()  # 仅在之前步骤成功时关闭
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            });
